version: '3.7'

services:

  web:
    container_name: django-REST-api
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "python manage.py migrate && python manage.py loaddata ./db/init_records.json && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    volumes:
      - .:/code
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db

  db:
    container_name: postgres
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    expose:
        - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      LC_ALL: ${LC_ALL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}